### ISSUE TITLE
tyf

### ISSUE THREAD

**Issue by AlexanderInHUST** [UniqueLab/uniquelab-tinc#15]
Port = 655
Subnet = 10.143.0.15/32

-----BEGIN RSA PUBLIC KEY-----
MIIBCgKCAQEAvnrFDFMzMK3iVzBPW9ApJKNeSKJiu2muFSFyLkyYZyGREHgtYSp0
+YjQMZNf546G6AwRQ2ulsjvz6VLy2f47r7t6XBleHC2MY3Ox0546djacG8/Lopvx
G106L+WcAsitgkEfy50k+PiirOreBH9LmkgV5bkQ7F0pJSA3dS4umDi7SrnybrFp
bQv563LZxlF1kXeMOjhODoVuoVXWgkOE9uwFE7y+tkondXVCxbap+FNVAC2n1H2j
lCY36DxT01pdAiGSd/sG0KhcrBXTINz5e6HYTuLvcGWe1jMDe7ZsVU+GujDKQ53g
TkGU8Iqvx+kZvwe5+xYbDkFH3B5VTVa+gQIDAQAB
-----END RSA PUBLIC KEY-----

**Comment by FluorineDog** [comment]
Added. Reopen this issus if it doesn't work.
BTW, I don't think 15 is an x that satisfies "100 <= x <= 254" :(

**Comment by AlexanderInHUST** [comment]
emmmmmm... I'm sorry that didn't noticed the range of the numbers... Maybe 155 would be a better choice...)

Port = 655
Subnet = 10.143.0.155/32

-----BEGIN RSA PUBLIC KEY-----
MIIBCgKCAQEA9SNoah2wKMa/0QalvqnRKYuBaWPvDHS5CquEdciYOiWCgDwAc5zK
s5BSbRUwtCseyUK+RxjIOffumiPLclT1wLFG+bGzf9ne5kZ1t5Riw6hnhKUJQOWt
mLJIJHWx7Hab6m1vG/rn9OImoDx8i1ZNMzBsLqDSXabJj4WGkMMGCEEluQLiDb5W
wTweVxTp+F9s091rR0TCCbl7ZkT2dRpBY8dnwbDtxoC1uS0H/XYKMCln9nhFMZwT
LlhRvuntv3SldPfhEXT+9yIvI6Rmib24JslJ1ITrJgrIiZzW5NvymqtfnevcLnum
mRZn6yGap63tm1NT5yGIPBQhjU7S1YJ8sQIDAQAB
-----END RSA PUBLIC KEY-----

**Comment by FluorineDog** [comment]
done

**Comment by AlexanderInHUST** [comment]
emmm... In fact, I've created a new pair of keys by using the script which you may not noticed...
