### ISSUE TITLE
new key

### ISSUE THREAD

**Issue by BlackDragonF** [UniqueLab/uniquelab-tinc#20]
Port = 655
Subnet = 10.143.0.149/32
-----BEGIN RSA PUBLIC KEY-----
MIIBCgKCAQEAu0/i0RiSHn++PloM19ApAIn3C9pIat4jtl89UIZNWbhiUSPo/ci+
2G5Gv7Yi6xF1OHre0Ll+A2SP2R799HOLsPWkKE/e3VVvhZjaf4+DVYLz+7u/7QxJ
msvgcrdmtuOcTIduTBfvl6jmBeC1Mx/S8JI/is/erQV5mD18UaOwSLw8lpj4hcBg
uNgYGp8uhZLwuEdb5nG/st9p9XFFyf62sUCYgpnWxRo3qTtO3qco4ruIXHbGLSrx
Uc5M+6i6jVgq516Lt+zMpeCfMxko23lpsHj2KbTUol4WydjDh1l8ka86yKj/9j7D
NeW4lJ3q53SySOjFC4Co/+1bQUU

**Comment by klx3300** [comment]
ILLEGAL FORMAT
please send a pull request WITH YOUR PUBLIC KEY FILE.
