### ISSUE TITLE
add request: husixu

### ISSUE THREAD

**Issue by husixu1** [UniqueLab/uniquelab-tinc#7]
Port = 655
Subnet = 10.143.0.222/32

-----BEGIN RSA PUBLIC KEY-----
MIIBCgKCAQEAsYnpFUGI0SUz2Whlqa2oizuIMtyA4ZKZyGQgQBMLEjEJVVO7NqFe
+b1jWghXv8eh/c5HlTAO+4bUtKLxK/jXE8kcpl+snTbE9A6HzaV1tpg+bu3mR8tj
MtB92qheB5ZjG/LU+C8SZoH9b+npt7FGqShfKn5XhEve8blcMc4v7lNpIZ+kAFBy
xP6n/iLv10h1I8N72gQ2qelex0t7GHg2sIbwCHrzv89Es7MpHyjRY286X5ldx1t8
e5GaFL2gmme4leQxzYL8Qtj92B724KOclaqhFX5jdSvDUA0hZzJ1GowEKcOOAm6Q
zKUinEOrPOktjOZgGo15+xB+2eZF2k1TewIDAQAB
-----END RSA PUBLIC KEY-----

**Comment by kaixili** [comment]
filename(hostname)?
